import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { Cinzel_Decorative } from "next/font/google";
import { cn } from "@/lib/utils"
const inter = Inter({ subsets: ["latin"] });
const cinzel_decorative = Cinzel_Decorative({
  subsets: ["latin"],
  weight:'400',
  variable: "--Cinzel_Decorative",
  display: 'swap',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={cn(
        "min-h-svh bg-background min-w-svw bg-gradient-to-b from-zinc-800 text-zinc-300  to-zinc-950  shadow-inner shadow-zinc-500 antialiased",
        cinzel_decorative.className
      )}
     >
        <Navbar/>
        {children}</body>
    </html>
  );
}
